rust:
  repo: https://github.com/matrix-org/matrix-rust-sdk
  ref: b994f47f1cb5d52b37a15728cbc5ff40286ad5aa
  manifestPath: bindings/matrix-sdk-ffi/Cargo.toml
web:
  workspace: true
  manifestPath: rust_modules/matrix-rust-sdk/bindings/wasm/Cargo.toml
  features: ["js", "indexeddb"]
  defaultFeatures: false
